<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<?php include_once( dirname(__FILE__) . "/campaign_config.php");?>

<html><head>
<link rel="shortcut icon" href="" type="image/x-icon" />
<link rel="icon" href="" type="image/x-icon" />
<link rel='stylesheet' type='text/css' href='index.css'>
<script src='videoChange.js' type='text/javascript'></script>
<title>Mattnet Campaign Login</title>
</head><body>

<div class='header'>
  <img src='banner.gif' class='header'>
</div>


<div class='main'>

<div class='article'>
<h3>About the Dramatic Universe Campaign</h3>

Many campaigns revolve around empires that are seeking to raise themselves to greatness, usually at the expense of their neighbors. They may do this in a "4X" (eXplore, eXpand, eXploit, and eXterminate) style, with varying amounts of detail and paperwork. They may use a published campaign, which dispenses with much of the detail and paperwork in favor of a limited situation or scope. Or they may use something with similar levels of scope, detail, and paperwork as a 4X campaign, but with some of the "X"s removed.

<p>This is not that sort of campaign.

<p><img src='./clipart_smoke.png' style='float:left'>

This campaign focuses not on the goals of the heads of state or the admirals, but on the captains. Instead of fighting a war, with territory marked out in controlled sectors and colonies of varying levels of productivity, the campaign is the storyboard of a television series. Anytime there is an odd subspace anomaly or dangerous space monster, you can always assume that both parties will show up to investigate at the same time.

<h3>What is a Campaign?</h3>

<img src='./clipart_map.png' style='float:right'>

A campaign is a system of mechanics that resolves a <a href='https://www.google.com/search?q=strategic' target="_BLANK">strategic</a> (macro) set of circumstances, that are then resolved using a different system of mechanics that is geared for <a href='https://www.google.com/search?q=tactical' target="_BLANK">tactical</a> (micro) circumstances. As applied here, the campaign creates a set of situations over several in-game years that starships (often the same starships) must find some sort of victory within. Each situation generated by this campaign are then resolved using <a href='http://starfleetgames.com/starfleetbattles.shtml' target="_BLANK">the Star Fleet Battles game system</a>, which is used to simulate the actions of a few starships when they encounter other starships (or space monsters, or colonies, or space anomolies).

<p>The advantage of a campaign system, besides generating interesting situations for the micro-level game, is that each starship develops a story about them. They become involved in an important event in history. They are damaged in action and sent back to port for repairs and refitting. They die gloriously in defense of the republic. Thier deeds are remembered because of the places they have been and the things they have done.
</div>

<div class='three'>
<div style='color:#993333;'><?php if( isset($_REQUEST['error']) ) echo $_REQUEST['error']; ?></div>
<h3>User Login</h3>
     <form accept-charset="UTF-8" action="Login/Login.php" id="" method="post" target="_SELF">
       <div class="">
          <label for="signup_name">User Name*</label>
          <br>
          <input id="signup_name" name="login" type="text" required>
       </div>
       <div class="">
          <label for="signup_pass">Password*</label>
          <br>
          <input id="signup_pass" name="pass" type="password" required>
       </div>
       <div class="">
          <input type="submit" value="Log In" id="" class="">
       </div>
       <div class="">
          <a href="Login/Login_lostpass.php">Lost Password?</a>
       </div>
     </form>
     <p><hr>
     <form accept-charset="UTF-8" action="Login/Login_new.php" id="" method="post" target="_SELF">
       <div class="">
          <label for="signup_name">User Name*</label>
          <br>
          <input id="signup_name" name="login" type="text" required>
       </div>
       <div class="">
          <input type="submit" value="Create Account" id="" class="">
       </div>
     </form>
<br><a href='<?php echo $RULES_LINK ?>' target='_BLANK' class='rules_link' title="Campaign Rules">Dramatic Universe Campaign Knowledge</a>
</form>

<h3>New to the Campaign?</h3>
Signing up is easy and free!
<br>To create an account, enter a login name and follow the instructions for adding details to your account. You're in! No payments, no spam, no advertisements. Just Star Trek wargaming goodness!

<p>Lost? Wondering how to use the software interface? Check out the <a href='docs/faq.html' target='_BLANK'>Frequently Asked Questions</a>
<p>Want to join the conversation? Check out our <a href='http://lists.mattnet.org/listinfo.cgi/sfbdrama-mattnet.org'>Mailing List</a>.

</div>

<div class='one'>
<h3>What's New</h3>
<p><b>01JAN21</b> With a new year comes a new set of units! Module G3 has been incorporated. This allows the full spread of ships from every product, including all of the products published since then, as well as many of the Captain's Logs. This allows us to confidently allow a whole host of new bugs to creep in, while getting rid of all of the old problems. Yay Progress!!
<p><b>07SEP20:</b> Several campaigns have been running so far. All will close down at the end of the year so we can have a newly-updated dataset. This dataset will include all of the published ships up to 2015, and some published later. A "kickstarter" goal was hit, so the Omega octant will be included as well!
<p><b>21OCT17:</b> We've started a new iteration of the campaign. This one reduces the bi-annual income to a mere stipend, and each player is expected to fight for the cash they use on the next season.
<p><b>14AUG17:</b> We are running on version 1.1. The campaign codebase has been posted to <a href='https://github.com/MattNet/dramatic-sfb' target='_BLANK'>github</a> under a GPL license.
<p><b>16MAR16:</b> Version 0.21a is up and running. This is the final release candidate.
<p><b>25FEB16:</b> <!-- Version 0.2a has been installed, giving the world a whole host of new bugs. This version imported a completed login portal and updated a little bit of art. -->
<p><b>20JUL15:</b> <!-- Version 0.13a has been installed.
<br>This includes the ability to change I/O modules mid-game and add player positions mid-game. -->
<p><b>29JUN15:</b> <!-- Version 0.12b has been installed.
<br>This includes a myriad of changes and bugfixes, such as allowing names for ships and empires, adding the NEWBORDER reward to scenarios, and changing the table names so multiple campaign packages can work side-by-side on the server. -->
<p><b>27APR15</b><!--  After over a year of development, version 0.1b has been released! -->
</div>
</div> <!-- end container -->

<div class='footer'>
<img src='commercial.thumb.png' width='300px' onclick='videoChange( this, "commercial" )'>
<br>Copyright &copy; 2015 - 2018 Matthew Potter
</div>

</body></html>
